rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

titles_from_headings:
  strip_title: true
  collections: true

feed:
  categories:
    - articles
    - blog

defaults:
  - scope:
      path: ""
      type: default
    values:
      tags: Other
